 default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: revrod
      dataset: revrod_ds
      threads: 1
      timeout_seconds: 300
      materialized: table
